# Generated by Django 5.2.3 on 2025-06-16 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('provider', models.CharField(choices=[('mbank', 'Mbank'), ('optimabank', 'OptimaBank'), ('bakaibank', 'BakaiBank'), ('other', 'Другое')], max_length=20, verbose_name='Платёжная система')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('paid', 'Оплачено'), ('failed', 'Ошибка'), ('refunded', 'Возврат'), ('canceled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('provider_payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа в системе')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
