# Generated by Django 5.2.3 on 2025-06-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_options_alter_review_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Хорошо'), (4, 'Превосходно')], default=3),
        ),
    ]
