# Generated by Django 5.2.3 on 2025-06-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
