# Generated by Django 5.2.3 on 2025-06-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Имя получателя')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('courier', models.IntegerField(choices=[(1, 'Cdek'), (2, 'Express'), (3, 'Местная доставка'), (4, 'Другое')], default=3, verbose_name='Служба доставки')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость доставки')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Трек-номер')),
                ('status', models.IntegerField(choices=[(1, 'Ожидает'), (2, 'В пути'), (3, 'Доставлено'), (4, 'Отменено')], default=1, verbose_name='Статус доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
