# Generated by Django 5.2.3 on 2025-06-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipping',
            options={'verbose_name': 'Доставка', 'verbose_name_plural': 'Доставки'},
        ),
    ]
