# Generated by Django 5.2.3 on 2025-06-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Новый'), (2, 'В обработке'), (3, 'Отправлен'), (4, 'Доставлен'), (5, 'Отменен')], default=1, max_length=20),
        ),
    ]
