# Generated by Django 5.2.3 on 2025-06-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Новый'), (2, 'В обработке'), (3, 'Отправлен'), (4, 'Доставлен'), (5, 'Отменен')], default=1),
        ),
    ]
