# Generated by Django 5.2.3 on 2025-06-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='SubCategory',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_items', verbose_name='Главаная картина товара'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='production',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Производство'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название товара'),
        ),
    ]
