# Generated by Django 5.2.3 on 2025-06-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_options_alter_cartitem_product'),
        ('orders', '0002_alter_order_options_alter_orderitem_options_and_more'),
        ('products', '0002_remove_items_subcategory_remove_subcategory_name_and_more'),
        ('reviews', '0002_alter_review_options_alter_review_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
    ]
