# Generated by Django 5.2.3 on 2025-06-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(default='бiphone', max_length=255, verbose_name='Название товара'),
            preserve_default=False,
        ),
    ]
