# Generated by Django 5.2.3 on 2025-06-16 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_subcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='color',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='model',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='production',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='title',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name',
            field=models.CharField(default='test', max_length=255, verbose_name='Подкатегория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category'),
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_items', verbose_name='Главаная картина товара')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена')),
                ('production', models.CharField(blank=True, max_length=255, null=True, verbose_name='Производство')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель')),
                ('is_available', models.BooleanField(default=False, verbose_name='Наличие')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Цвет')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.subcategory')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('order',),
            },
        ),
    ]
